// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: msgstruct.proto

package textsecure

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OutMessage_Type int32

const (
	OutMessage_UNKNOWN       OutMessage_Type = 0
	OutMessage_CIPHERTEXT    OutMessage_Type = 1
	OutMessage_KEY_EXCHANGE  OutMessage_Type = 2
	OutMessage_PREKEY_BUNDLE OutMessage_Type = 3
	OutMessage_RECEIPT       OutMessage_Type = 5
)

// Enum value maps for OutMessage_Type.
var (
	OutMessage_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "CIPHERTEXT",
		2: "KEY_EXCHANGE",
		3: "PREKEY_BUNDLE",
		5: "RECEIPT",
	}
	OutMessage_Type_value = map[string]int32{
		"UNKNOWN":       0,
		"CIPHERTEXT":    1,
		"KEY_EXCHANGE":  2,
		"PREKEY_BUNDLE": 3,
		"RECEIPT":       5,
	}
)

func (x OutMessage_Type) Enum() *OutMessage_Type {
	p := new(OutMessage_Type)
	*p = x
	return p
}

func (x OutMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_msgstruct_proto_enumTypes[0].Descriptor()
}

func (OutMessage_Type) Type() protoreflect.EnumType {
	return &file_msgstruct_proto_enumTypes[0]
}

func (x OutMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutMessage_Type.Descriptor instead.
func (OutMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_msgstruct_proto_rawDescGZIP(), []int{0, 0}
}

type WebSocketMessage_Type int32

const (
	WebSocketMessage_UNKNOWN  WebSocketMessage_Type = 0
	WebSocketMessage_REQUEST  WebSocketMessage_Type = 1
	WebSocketMessage_RESPONSE WebSocketMessage_Type = 2
)

// Enum value maps for WebSocketMessage_Type.
var (
	WebSocketMessage_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "REQUEST",
		2: "RESPONSE",
	}
	WebSocketMessage_Type_value = map[string]int32{
		"UNKNOWN":  0,
		"REQUEST":  1,
		"RESPONSE": 2,
	}
)

func (x WebSocketMessage_Type) Enum() *WebSocketMessage_Type {
	p := new(WebSocketMessage_Type)
	*p = x
	return p
}

func (x WebSocketMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebSocketMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_msgstruct_proto_enumTypes[1].Descriptor()
}

func (WebSocketMessage_Type) Type() protoreflect.EnumType {
	return &file_msgstruct_proto_enumTypes[1]
}

func (x WebSocketMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebSocketMessage_Type.Descriptor instead.
func (WebSocketMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_msgstruct_proto_rawDescGZIP(), []int{3, 0}
}

type OutMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          OutMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=textsecure.OutMessage_Type" json:"type,omitempty"` // [default = CIPHERTEXT]
	Source        string          `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Relay         string          `protobuf:"bytes,3,opt,name=relay,proto3" json:"relay,omitempty"`
	Body          []byte          `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Timestamp     int64           `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LegacyMessage []byte          `protobuf:"bytes,6,opt,name=legacyMessage,proto3" json:"legacyMessage,omitempty"`
	SourceDevice  int64           `protobuf:"varint,7,opt,name=sourceDevice,proto3" json:"sourceDevice,omitempty"`
	Content       []byte          `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *OutMessage) Reset() {
	*x = OutMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgstruct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutMessage) ProtoMessage() {}

func (x *OutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msgstruct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutMessage.ProtoReflect.Descriptor instead.
func (*OutMessage) Descriptor() ([]byte, []int) {
	return file_msgstruct_proto_rawDescGZIP(), []int{0}
}

func (x *OutMessage) GetType() OutMessage_Type {
	if x != nil {
		return x.Type
	}
	return OutMessage_UNKNOWN
}

func (x *OutMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OutMessage) GetRelay() string {
	if x != nil {
		return x.Relay
	}
	return ""
}

func (x *OutMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OutMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OutMessage) GetLegacyMessage() []byte {
	if x != nil {
		return x.LegacyMessage
	}
	return nil
}

func (x *OutMessage) GetSourceDevice() int64 {
	if x != nil {
		return x.SourceDevice
	}
	return 0
}

func (x *OutMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WebSocketRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verb    string `protobuf:"bytes,1,opt,name=verb,proto3" json:"verb,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers string `protobuf:"bytes,5,opt,name=headers,proto3" json:"headers,omitempty"`
	Body    []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Id      uint64 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WebSocketRequestMessage) Reset() {
	*x = WebSocketRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgstruct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebSocketRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketRequestMessage) ProtoMessage() {}

func (x *WebSocketRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msgstruct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketRequestMessage.ProtoReflect.Descriptor instead.
func (*WebSocketRequestMessage) Descriptor() ([]byte, []int) {
	return file_msgstruct_proto_rawDescGZIP(), []int{1}
}

func (x *WebSocketRequestMessage) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *WebSocketRequestMessage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WebSocketRequestMessage) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *WebSocketRequestMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WebSocketRequestMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WebSocketResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status  uint32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Headers string `protobuf:"bytes,5,opt,name=headers,proto3" json:"headers,omitempty"`
	Body    []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *WebSocketResponseMessage) Reset() {
	*x = WebSocketResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgstruct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebSocketResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketResponseMessage) ProtoMessage() {}

func (x *WebSocketResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msgstruct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketResponseMessage.ProtoReflect.Descriptor instead.
func (*WebSocketResponseMessage) Descriptor() ([]byte, []int) {
	return file_msgstruct_proto_rawDescGZIP(), []int{2}
}

func (x *WebSocketResponseMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WebSocketResponseMessage) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WebSocketResponseMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WebSocketResponseMessage) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

func (x *WebSocketResponseMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type WebSocketMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     WebSocketMessage_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=textsecure.WebSocketMessage_Type" json:"type,omitempty"`
	Request  *WebSocketRequestMessage  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	Response *WebSocketResponseMessage `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgstruct_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msgstruct_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_msgstruct_proto_rawDescGZIP(), []int{3}
}

func (x *WebSocketMessage) GetType() WebSocketMessage_Type {
	if x != nil {
		return x.Type
	}
	return WebSocketMessage_UNKNOWN
}

func (x *WebSocketMessage) GetRequest() *WebSocketRequestMessage {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *WebSocketMessage) GetResponse() *WebSocketResponseMessage {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_msgstruct_proto protoreflect.FileDescriptor

var file_msgstruct_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x73, 0x67, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x22, 0xd8, 0x02,
	0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x74, 0x65, 0x78,
	0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x24, 0x0a,
	0x0d, 0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0x55, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x49, 0x50, 0x48, 0x45, 0x52,
	0x54, 0x45, 0x58, 0x54, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x45, 0x59, 0x5f, 0x45, 0x58,
	0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x52, 0x45, 0x4b,
	0x45, 0x59, 0x5f, 0x42, 0x55, 0x4e, 0x44, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52,
	0x45, 0x43, 0x45, 0x49, 0x50, 0x54, 0x10, 0x05, 0x22, 0x7f, 0x0a, 0x17, 0x57, 0x65, 0x62, 0x53,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x65, 0x72, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x76, 0x65, 0x72, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x18, 0x57, 0x65,
	0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xfa, 0x01, 0x0a, 0x10, 0x57, 0x65, 0x62, 0x53, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x74, 0x65, 0x78, 0x74,
	0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x2e, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x40, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x2e, 0x57, 0x65, 0x62, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x2e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53,
	0x45, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgstruct_proto_rawDescOnce sync.Once
	file_msgstruct_proto_rawDescData = file_msgstruct_proto_rawDesc
)

func file_msgstruct_proto_rawDescGZIP() []byte {
	file_msgstruct_proto_rawDescOnce.Do(func() {
		file_msgstruct_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgstruct_proto_rawDescData)
	})
	return file_msgstruct_proto_rawDescData
}

var file_msgstruct_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_msgstruct_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msgstruct_proto_goTypes = []interface{}{
	(OutMessage_Type)(0),             // 0: textsecure.OutMessage.Type
	(WebSocketMessage_Type)(0),       // 1: textsecure.WebSocketMessage.Type
	(*OutMessage)(nil),               // 2: textsecure.OutMessage
	(*WebSocketRequestMessage)(nil),  // 3: textsecure.WebSocketRequestMessage
	(*WebSocketResponseMessage)(nil), // 4: textsecure.WebSocketResponseMessage
	(*WebSocketMessage)(nil),         // 5: textsecure.WebSocketMessage
}
var file_msgstruct_proto_depIdxs = []int32{
	0, // 0: textsecure.OutMessage.type:type_name -> textsecure.OutMessage.Type
	1, // 1: textsecure.WebSocketMessage.type:type_name -> textsecure.WebSocketMessage.Type
	3, // 2: textsecure.WebSocketMessage.request:type_name -> textsecure.WebSocketRequestMessage
	4, // 3: textsecure.WebSocketMessage.response:type_name -> textsecure.WebSocketResponseMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msgstruct_proto_init() }
func file_msgstruct_proto_init() {
	if File_msgstruct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgstruct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgstruct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebSocketRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgstruct_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebSocketResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgstruct_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebSocketMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgstruct_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgstruct_proto_goTypes,
		DependencyIndexes: file_msgstruct_proto_depIdxs,
		EnumInfos:         file_msgstruct_proto_enumTypes,
		MessageInfos:      file_msgstruct_proto_msgTypes,
	}.Build()
	File_msgstruct_proto = out.File
	file_msgstruct_proto_rawDesc = nil
	file_msgstruct_proto_goTypes = nil
	file_msgstruct_proto_depIdxs = nil
}
