// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: proto/queue_protocol.proto

package textsecure

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SendMessageToDevice_Type int32

const (
	SendMessageToDevice_UNKNOWN         SendMessageToDevice_Type = 0
	SendMessageToDevice_CHANNEL_MESSAGE SendMessageToDevice_Type = 1
)

// Enum value maps for SendMessageToDevice_Type.
var (
	SendMessageToDevice_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "CHANNEL_MESSAGE",
	}
	SendMessageToDevice_Type_value = map[string]int32{
		"UNKNOWN":         0,
		"CHANNEL_MESSAGE": 1,
	}
)

func (x SendMessageToDevice_Type) Enum() *SendMessageToDevice_Type {
	p := new(SendMessageToDevice_Type)
	*p = x
	return p
}

func (x SendMessageToDevice_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendMessageToDevice_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_queue_protocol_proto_enumTypes[0].Descriptor()
}

func (SendMessageToDevice_Type) Type() protoreflect.EnumType {
	return &file_proto_queue_protocol_proto_enumTypes[0]
}

func (x SendMessageToDevice_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendMessageToDevice_Type.Descriptor instead.
func (SendMessageToDevice_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_queue_protocol_proto_rawDescGZIP(), []int{5, 0}
}

type SendSMS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SendSMS) Reset() {
	*x = SendSMS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_queue_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendSMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMS) ProtoMessage() {}

func (x *SendSMS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMS.ProtoReflect.Descriptor instead.
func (*SendSMS) Descriptor() ([]byte, []int) {
	return file_proto_queue_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *SendSMS) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SendSMS) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SendVoiceSMS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Locale      string `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
}

func (x *SendVoiceSMS) Reset() {
	*x = SendVoiceSMS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_queue_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendVoiceSMS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVoiceSMS) ProtoMessage() {}

func (x *SendVoiceSMS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVoiceSMS.ProtoReflect.Descriptor instead.
func (*SendVoiceSMS) Descriptor() ([]byte, []int) {
	return file_proto_queue_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *SendVoiceSMS) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SendVoiceSMS) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendVoiceSMS) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type DeleteObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bucket string `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
}

func (x *DeleteObject) Reset() {
	*x = DeleteObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_queue_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObject) ProtoMessage() {}

func (x *DeleteObject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObject.ProtoReflect.Descriptor instead.
func (*DeleteObject) Descriptor() ([]byte, []int) {
	return file_proto_queue_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteObject) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteObject) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type SendApnMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApnId          string `protobuf:"bytes,1,opt,name=apn_id,json=apnId,proto3" json:"apn_id,omitempty"`
	Topic          string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Number         string `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	DeviceId       int64  `protobuf:"varint,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	IsVoip         bool   `protobuf:"varint,5,opt,name=isVoip,proto3" json:"isVoip,omitempty"`
	Message        string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ExpirationTime int64  `protobuf:"varint,7,opt,name=expirationTime,proto3" json:"expirationTime,omitempty"`
}

func (x *SendApnMessage) Reset() {
	*x = SendApnMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_queue_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendApnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendApnMessage) ProtoMessage() {}

func (x *SendApnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendApnMessage.ProtoReflect.Descriptor instead.
func (*SendApnMessage) Descriptor() ([]byte, []int) {
	return file_proto_queue_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *SendApnMessage) GetApnId() string {
	if x != nil {
		return x.ApnId
	}
	return ""
}

func (x *SendApnMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendApnMessage) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *SendApnMessage) GetDeviceId() int64 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *SendApnMessage) GetIsVoip() bool {
	if x != nil {
		return x.IsVoip
	}
	return false
}

func (x *SendApnMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendApnMessage) GetExpirationTime() int64 {
	if x != nil {
		return x.ExpirationTime
	}
	return 0
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_queue_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_queue_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *Device) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SendMessageToDevice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    SendMessageToDevice_Type `protobuf:"varint,1,opt,name=type,proto3,enum=textsecure.SendMessageToDevice_Type" json:"type,omitempty"`
	Content []byte                   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Devices []*Device                `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *SendMessageToDevice) Reset() {
	*x = SendMessageToDevice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_queue_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageToDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToDevice) ProtoMessage() {}

func (x *SendMessageToDevice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_queue_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToDevice.ProtoReflect.Descriptor instead.
func (*SendMessageToDevice) Descriptor() ([]byte, []int) {
	return file_proto_queue_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageToDevice) GetType() SendMessageToDevice_Type {
	if x != nil {
		return x.Type
	}
	return SendMessageToDevice_UNKNOWN
}

func (x *SendMessageToDevice) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageToDevice) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_proto_queue_protocol_proto protoreflect.FileDescriptor

var file_proto_queue_protocol_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65,
	0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x22, 0x3f, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x4d, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x5c, 0x0a, 0x0c, 0x53, 0x65, 0x6e,
	0x64, 0x56, 0x6f, 0x69, 0x63, 0x65, 0x53, 0x4d, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x22, 0x38, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x22, 0xcb, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x70, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x56, 0x6f, 0x69, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x56, 0x6f, 0x69, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x2c, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0xc1, 0x01,
	0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x78,
	0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_queue_protocol_proto_rawDescOnce sync.Once
	file_proto_queue_protocol_proto_rawDescData = file_proto_queue_protocol_proto_rawDesc
)

func file_proto_queue_protocol_proto_rawDescGZIP() []byte {
	file_proto_queue_protocol_proto_rawDescOnce.Do(func() {
		file_proto_queue_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_queue_protocol_proto_rawDescData)
	})
	return file_proto_queue_protocol_proto_rawDescData
}

var file_proto_queue_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_queue_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_queue_protocol_proto_goTypes = []interface{}{
	(SendMessageToDevice_Type)(0), // 0: textsecure.SendMessageToDevice.Type
	(*SendSMS)(nil),               // 1: textsecure.SendSMS
	(*SendVoiceSMS)(nil),          // 2: textsecure.SendVoiceSMS
	(*DeleteObject)(nil),          // 3: textsecure.DeleteObject
	(*SendApnMessage)(nil),        // 4: textsecure.SendApnMessage
	(*Device)(nil),                // 5: textsecure.Device
	(*SendMessageToDevice)(nil),   // 6: textsecure.SendMessageToDevice
}
var file_proto_queue_protocol_proto_depIdxs = []int32{
	0, // 0: textsecure.SendMessageToDevice.type:type_name -> textsecure.SendMessageToDevice.Type
	5, // 1: textsecure.SendMessageToDevice.devices:type_name -> textsecure.Device
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_queue_protocol_proto_init() }
func file_proto_queue_protocol_proto_init() {
	if File_proto_queue_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_queue_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendSMS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_queue_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendVoiceSMS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_queue_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_queue_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendApnMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_queue_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_queue_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageToDevice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_queue_protocol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_queue_protocol_proto_goTypes,
		DependencyIndexes: file_proto_queue_protocol_proto_depIdxs,
		EnumInfos:         file_proto_queue_protocol_proto_enumTypes,
		MessageInfos:      file_proto_queue_protocol_proto_msgTypes,
	}.Build()
	File_proto_queue_protocol_proto = out.File
	file_proto_queue_protocol_proto_rawDesc = nil
	file_proto_queue_protocol_proto_goTypes = nil
	file_proto_queue_protocol_proto_depIdxs = nil
}
