//*
// Copyright (C) 2013 - 2015 Open WhisperSystems
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.1
// source: proto/TextSecure.proto

package textsecure

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Envelope_Type int32

const (
	Envelope_UNKNOWN             Envelope_Type = 0
	Envelope_CIPHERTEXT          Envelope_Type = 1
	Envelope_KEY_EXCHANGE        Envelope_Type = 2
	Envelope_PREKEY_BUNDLE       Envelope_Type = 3
	Envelope_RECEIPT             Envelope_Type = 5 //收据
	Envelope_UNIDENTIFIED_SENDER Envelope_Type = 6
)

// Enum value maps for Envelope_Type.
var (
	Envelope_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "CIPHERTEXT",
		2: "KEY_EXCHANGE",
		3: "PREKEY_BUNDLE",
		5: "RECEIPT",
		6: "UNIDENTIFIED_SENDER",
	}
	Envelope_Type_value = map[string]int32{
		"UNKNOWN":             0,
		"CIPHERTEXT":          1,
		"KEY_EXCHANGE":        2,
		"PREKEY_BUNDLE":       3,
		"RECEIPT":             5,
		"UNIDENTIFIED_SENDER": 6,
	}
)

func (x Envelope_Type) Enum() *Envelope_Type {
	p := new(Envelope_Type)
	*p = x
	return p
}

func (x Envelope_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Envelope_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_TextSecure_proto_enumTypes[0].Descriptor()
}

func (Envelope_Type) Type() protoreflect.EnumType {
	return &file_proto_TextSecure_proto_enumTypes[0]
}

func (x Envelope_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Envelope_Type.Descriptor instead.
func (Envelope_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_TextSecure_proto_rawDescGZIP(), []int{0, 0}
}

type Envelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type            Envelope_Type `protobuf:"varint,1,opt,name=type,proto3,enum=textsecure.Envelope_Type" json:"type,omitempty"`
	Source          string        `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	SourceUuid      string        `protobuf:"bytes,11,opt,name=sourceUuid,proto3" json:"sourceUuid,omitempty"`
	SourceDevice    uint32        `protobuf:"varint,7,opt,name=sourceDevice,proto3" json:"sourceDevice,omitempty"`
	Relay           string        `protobuf:"bytes,3,opt,name=relay,proto3" json:"relay,omitempty"`
	Timestamp       uint64        `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LegacyMessage   []byte        `protobuf:"bytes,6,opt,name=legacyMessage,proto3" json:"legacyMessage,omitempty"` // Contains an encrypted DataMessage XXX -- Remove after 10/01/15
	Content         []byte        `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`             // Contains an encrypted Content
	ServerGuid      string        `protobuf:"bytes,9,opt,name=serverGuid,proto3" json:"serverGuid,omitempty"`
	ServerTimestamp uint64        `protobuf:"varint,10,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TextSecure_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TextSecure_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_TextSecure_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetType() Envelope_Type {
	if x != nil {
		return x.Type
	}
	return Envelope_UNKNOWN
}

func (x *Envelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Envelope) GetSourceUuid() string {
	if x != nil {
		return x.SourceUuid
	}
	return ""
}

func (x *Envelope) GetSourceDevice() uint32 {
	if x != nil {
		return x.SourceDevice
	}
	return 0
}

func (x *Envelope) GetRelay() string {
	if x != nil {
		return x.Relay
	}
	return ""
}

func (x *Envelope) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Envelope) GetLegacyMessage() []byte {
	if x != nil {
		return x.LegacyMessage
	}
	return nil
}

func (x *Envelope) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Envelope) GetServerGuid() string {
	if x != nil {
		return x.ServerGuid
	}
	return ""
}

func (x *Envelope) GetServerTimestamp() uint64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

type ProvisioningUuid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *ProvisioningUuid) Reset() {
	*x = ProvisioningUuid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TextSecure_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvisioningUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningUuid) ProtoMessage() {}

func (x *ProvisioningUuid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TextSecure_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisioningUuid.ProtoReflect.Descriptor instead.
func (*ProvisioningUuid) Descriptor() ([]byte, []int) {
	return file_proto_TextSecure_proto_rawDescGZIP(), []int{1}
}

func (x *ProvisioningUuid) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ServerCertificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certificate []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Signature   []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ServerCertificate) Reset() {
	*x = ServerCertificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TextSecure_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCertificate) ProtoMessage() {}

func (x *ServerCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TextSecure_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCertificate.ProtoReflect.Descriptor instead.
func (*ServerCertificate) Descriptor() ([]byte, []int) {
	return file_proto_TextSecure_proto_rawDescGZIP(), []int{2}
}

func (x *ServerCertificate) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *ServerCertificate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SenderCertificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certificate []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Signature   []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SenderCertificate) Reset() {
	*x = SenderCertificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TextSecure_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderCertificate) ProtoMessage() {}

func (x *SenderCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TextSecure_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderCertificate.ProtoReflect.Descriptor instead.
func (*SenderCertificate) Descriptor() ([]byte, []int) {
	return file_proto_TextSecure_proto_rawDescGZIP(), []int{3}
}

func (x *SenderCertificate) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *SenderCertificate) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ServerCertificate_Certificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ServerCertificate_Certificate) Reset() {
	*x = ServerCertificate_Certificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TextSecure_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerCertificate_Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCertificate_Certificate) ProtoMessage() {}

func (x *ServerCertificate_Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TextSecure_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCertificate_Certificate.ProtoReflect.Descriptor instead.
func (*ServerCertificate_Certificate) Descriptor() ([]byte, []int) {
	return file_proto_TextSecure_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ServerCertificate_Certificate) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerCertificate_Certificate) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type SenderCertificate_Certificate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender       string             `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderUuid   string             `protobuf:"bytes,6,opt,name=senderUuid,proto3" json:"senderUuid,omitempty"`
	SenderDevice uint32             `protobuf:"varint,2,opt,name=senderDevice,proto3" json:"senderDevice,omitempty"`
	Expires      uint64             `protobuf:"fixed64,3,opt,name=expires,proto3" json:"expires,omitempty"`
	IdentityKey  []byte             `protobuf:"bytes,4,opt,name=identityKey,proto3" json:"identityKey,omitempty"`
	Signer       *ServerCertificate `protobuf:"bytes,5,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (x *SenderCertificate_Certificate) Reset() {
	*x = SenderCertificate_Certificate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_TextSecure_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderCertificate_Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderCertificate_Certificate) ProtoMessage() {}

func (x *SenderCertificate_Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_TextSecure_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderCertificate_Certificate.ProtoReflect.Descriptor instead.
func (*SenderCertificate_Certificate) Descriptor() ([]byte, []int) {
	return file_proto_TextSecure_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SenderCertificate_Certificate) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SenderCertificate_Certificate) GetSenderUuid() string {
	if x != nil {
		return x.SenderUuid
	}
	return ""
}

func (x *SenderCertificate_Certificate) GetSenderDevice() uint32 {
	if x != nil {
		return x.SenderDevice
	}
	return 0
}

func (x *SenderCertificate_Certificate) GetExpires() uint64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *SenderCertificate_Certificate) GetIdentityKey() []byte {
	if x != nil {
		return x.IdentityKey
	}
	return nil
}

func (x *SenderCertificate_Certificate) GetSigner() *ServerCertificate {
	if x != nil {
		return x.Signer
	}
	return nil
}

var File_proto_TextSecure_proto protoreflect.FileDescriptor

var file_proto_TextSecure_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x54, 0x65, 0x78, 0x74, 0x53, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65,
	0x63, 0x75, 0x72, 0x65, 0x22, 0xc4, 0x03, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x12, 0x2d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x19, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x45, 0x6e, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x6c,
	0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x75, 0x69, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x75, 0x69, 0x64,
	0x12, 0x29, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x6e, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x49, 0x50, 0x48, 0x45, 0x52, 0x54, 0x45, 0x58, 0x54, 0x10, 0x01,
	0x12, 0x10, 0x0a, 0x0c, 0x4b, 0x45, 0x59, 0x5f, 0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x52, 0x45, 0x4b, 0x45, 0x59, 0x5f, 0x42, 0x55, 0x4e,
	0x44, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x43, 0x45, 0x49, 0x50, 0x54,
	0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x4e, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x10, 0x06, 0x22, 0x26, 0x0a, 0x10, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x22, 0x84, 0x01, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b,
	0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x1a, 0x2f, 0x0a, 0x0b, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xb2, 0x02, 0x0a, 0x11, 0x53,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x1a, 0xdc, 0x01, 0x0a, 0x0b, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x07, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x73,
	0x65, 0x63, 0x75, 0x72, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_TextSecure_proto_rawDescOnce sync.Once
	file_proto_TextSecure_proto_rawDescData = file_proto_TextSecure_proto_rawDesc
)

func file_proto_TextSecure_proto_rawDescGZIP() []byte {
	file_proto_TextSecure_proto_rawDescOnce.Do(func() {
		file_proto_TextSecure_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_TextSecure_proto_rawDescData)
	})
	return file_proto_TextSecure_proto_rawDescData
}

var file_proto_TextSecure_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_TextSecure_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_TextSecure_proto_goTypes = []interface{}{
	(Envelope_Type)(0),                    // 0: textsecure.Envelope.Type
	(*Envelope)(nil),                      // 1: textsecure.Envelope
	(*ProvisioningUuid)(nil),              // 2: textsecure.ProvisioningUuid
	(*ServerCertificate)(nil),             // 3: textsecure.ServerCertificate
	(*SenderCertificate)(nil),             // 4: textsecure.SenderCertificate
	(*ServerCertificate_Certificate)(nil), // 5: textsecure.ServerCertificate.Certificate
	(*SenderCertificate_Certificate)(nil), // 6: textsecure.SenderCertificate.Certificate
}
var file_proto_TextSecure_proto_depIdxs = []int32{
	0, // 0: textsecure.Envelope.type:type_name -> textsecure.Envelope.Type
	3, // 1: textsecure.SenderCertificate.Certificate.signer:type_name -> textsecure.ServerCertificate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_TextSecure_proto_init() }
func file_proto_TextSecure_proto_init() {
	if File_proto_TextSecure_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_TextSecure_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Envelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TextSecure_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvisioningUuid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TextSecure_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerCertificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TextSecure_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderCertificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TextSecure_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerCertificate_Certificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_TextSecure_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderCertificate_Certificate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_TextSecure_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_TextSecure_proto_goTypes,
		DependencyIndexes: file_proto_TextSecure_proto_depIdxs,
		EnumInfos:         file_proto_TextSecure_proto_enumTypes,
		MessageInfos:      file_proto_TextSecure_proto_msgTypes,
	}.Build()
	File_proto_TextSecure_proto = out.File
	file_proto_TextSecure_proto_rawDesc = nil
	file_proto_TextSecure_proto_goTypes = nil
	file_proto_TextSecure_proto_depIdxs = nil
}
