// Code generated by goctl. DO NOT EDIT!
// Source: hello.proto

package main

import (
	"flag"
	"fmt"

	"secret-im/service/signalserver/cmd/rpc/hello/hello_rpc"
	"secret-im/service/signalserver/cmd/rpc/hello/internal/config"
	"secret-im/service/signalserver/cmd/rpc/hello/internal/server"
	"secret-im/service/signalserver/cmd/rpc/hello/internal/svc"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

var configFile = flag.String("f", "etc/hellorpc.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewHelloRpcServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
		hello_rpc.RegisterHelloRpcServer(grpcServer, srv)
	})
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
