GET http://127.0.0.1:38888/v1/certificate/delivery
Content-Type: application/json
x-user-name: otcexchange
Authorization: Basic ODRmYzVhMTItYTYyZS00OTNmLTg5NjMtMzY0NDdmZjMxMjQ1OnV3OFJyQ1AwdDhGVWQ1anpVR0xrVXI1Nw==
