
# 某个帐号key的总数
GET http://127.0.0.1:38888/v2/keys/
Content-Type: application/json
x-user-name: liguozhen232
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjEzMjQ1MDAsImlhdCI6MTYyMTIzODEwMCwibmFtZSI6Im90Y2V4Y2hhbmdlIn0.wGlrSPtsAkChPSMLF6j1hi3VmzWM49GMXYztzTtB_2U

###
# 获取帐号下某个设备的prekey
GET http://127.0.0.1:38888/v2/keys/liguozhen232/*
Content-Type: application/json
x-user-name:liguozhen232
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjEzMjQ1MDAsImlhdCI6MTYyMTIzODEwMCwibmFtZSI6Im90Y2V4Y2hhbmdlIn0.wGlrSPtsAkChPSMLF6j1hi3VmzWM49GMXYztzTtB_2U




###
# 上传key
PUT http://127.0.0.1:38888/v2/keys
Content-Type: application/json
x-user-name: liguozhen232
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjEzMjQ1MDAsImlhdCI6MTYyMTIzODEwMCwibmFtZSI6Im90Y2V4Y2hhbmdlIn0.wGlrSPtsAkChPSMLF6j1hi3VmzWM49GMXYztzTtB_2U

{
  "identityKey":"identityKey",
  "signedPreKey":{
    "signature": "signature",
    "keyId": 1,
    "publicKey": "54"
  },

  "preKeys":[
    {
      "keyId": 0,
      "publicKey": "pk1"
    },
    {
      "keyId": 1,
      "publicKey": "pk2"
    }
  ]

}