// Code generated by goctl. DO NOT EDIT!
// Source: hello.proto

package server

import (
	"context"

	"privatedb/hello-rpc/hello"
	"privatedb/hello-rpc/internal/logic"
	"privatedb/hello-rpc/internal/svc"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServer) Ping(ctx context.Context, in *hello.Request) (*hello.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *HelloServer) Add(ctx context.Context, in *hello.AddReq) (*hello.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
