// Code generated by goctl. DO NOT EDIT!
// Source: hello.proto

package server

import (
	"context"

	"secret-im/service/signalserver/cmd/rpc/hello/hello_rpc"
	"secret-im/service/signalserver/cmd/rpc/hello/internal/logic"
	"secret-im/service/signalserver/cmd/rpc/hello/internal/svc"
)

type HelloRpcServer struct {
	svcCtx *svc.ServiceContext
}

func NewHelloRpcServer(svcCtx *svc.ServiceContext) *HelloRpcServer {
	return &HelloRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloRpcServer) Ping(ctx context.Context, in *hello_rpc.Request) (*hello_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *HelloRpcServer) GetUser(ctx context.Context, in *hello_rpc.IdReq) (*hello_rpc.UserInfoReply, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
