// Code generated by goctl. DO NOT EDIT!
// Source: bookstore.proto

package main

import (
	"flag"
	"fmt"

	"secret-im/service/signalserver/cmd/rpc/bookstore/bookstore"
	"secret-im/service/signalserver/cmd/rpc/bookstore/internal/config"
	"secret-im/service/signalserver/cmd/rpc/bookstore/internal/server"
	"secret-im/service/signalserver/cmd/rpc/bookstore/internal/svc"
	"secret-im/service/signalserver/cmd/rpc/interceptor"

	"github.com/tal-tech/go-zero/core/conf"
	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"

)

var configFile = flag.String("f", "etc/bookstore.yaml", "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)
	srv := server.NewBookstoreServer(ctx)

	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {

		bookstore.RegisterBookstoreServer(grpcServer, srv)
	})

	s.AddUnaryInterceptors(interceptor.RateLimitInterceptor) //添加自定义拦截器
	defer s.Stop()

	fmt.Printf("Starting rpc server at %s...\n", c.ListenOn)
	s.Start()
}
