
# curl -i "http://localhost:8888/add?book=go-zero&price=10"
GET http://localhost:8888/add?book=go-zero&price=10

###
# curl -i "http://localhost:8888/check?book=go-zero"
GET http://localhost:8888/check?book=go-zero

###



###
GET http://127.0.0.1:8888/user/info
Content-Type: application/json
x-User-Id: 1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTQxNDYxNDksImlhdCI6MTYxNDA1OTc0OSwidXNlcklkIjoxfQ.7qdmQG2vbzyWgvXx-5Zh1jPfxS--0Z8Ild9s5GgT8eI

<> 2021-02-23T135639.200.json



###
POST http://127.0.0.1:8888/user/login
Content-Type: application/json

{
  "username":"admin",
  "password":"666666",
  "mobile":"19988888888"
}


<> 2021-02-23T135549.200.json
<> 2021-02-23T135534.200.json



###
POST http://127.0.0.1:8888/user/register
Content-Type: application/json

{
  "username":"admin",
  "password":"666666",
  "mobile":"19988888888"
}



