// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"privatedb/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/index",
				Handler: IndexHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/ping",
				Handler: pingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: registerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Usercheck},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: userInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EOSUserCheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/msg/add",
					Handler: AddmsgHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/msg/get",
					Handler: GetmsgHandler(serverCtx),
				},
			}...,
		),
	)

	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.EOSUserCheck},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/payment/types",
					Handler: GetPaymentTypeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/payment/account",
					Handler: GetPayAccountHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api/payment/upsert",
					Handler: UpsertPayAccountHandler(serverCtx),
				},
			}...,
		),
	)
}
