
# curl -i "http://localhost:8888/add?book=go-zero&price=10"
GET http://localhost:8888/add?book=go-zero&price=10

###
# curl -i "http://localhost:8888/check?book=go-zero"
GET http://localhost:8888/check?book=go-zero

###



###
GET http://127.0.0.1:8888/user/info
Content-Type: application/json
x-User-Id: 1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTQ3NjI4MjYsImlhdCI6MTYxNDY3NjQyNiwidXNlcklkIjoxfQ.MvqQUsDoo_14wU2QmXXyskYQnB7AUCyEhxtBDokE9No

<> 2021-02-23T135639.200.json



###
POST http://127.0.0.1:8888/user/login
Content-Type: application/json

{
  "username":"admin",
  "password":"666666",
  "mobile":"19988888888"
}


<> 2021-02-23T135549.200.json
<> 2021-02-23T135534.200.json



###
POST http://127.0.0.1:8888/user/register
Content-Type: application/json

{
  "username":"admin",
  "password":"666666",
  "mobile":"19988888888"
}
###

POST http://127.0.0.1:8888/api/v1/adxuser/login
Content-Type: application/json

{
"name":"otcexchange",
"sign":"SIG_K1_Jz4KTq5v3dhcRKYehza6NRF5SxZaEzdPiVohRhX5SqoDCjmjf6hh3vyqfFHzEUagWZHC3L6G6SaJvKdH3UWEVwJRLWc6jL"

}


###
GET http://127.0.0.1:8888//api/v1/adxuser/ws
x-user-name: otcexchange
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTQ3NjI4MjYsImlhdCI6MTYxNDY3NjQyNiwidXNlcklkIjoxfQ.MvqQUsDoo_14wU2QmXXyskYQnB7AUCyEhxtBDokE9No
